language: rust

matrix:
  include:
  - rust: nightly
    name: "Linux, nightly"
  - rust: nightly
    name: "Linux, nightly, no-default-features"
    script:
    - cargo build --verbose --no-default-features --features=nightly
    - cargo test --verbose --no-default-features --features=nightly
  - rust: stable
    name: "Linux, stable"

